attributes:
  fuel-plugin-novadocker_text:
    value: 'cirros'
    label: 'Containers list'
    description: 'List of docker container to automatically download'
    weight: 25
    type: "text"
    # Checkbox
  fuel-plugin-novadocker_checkbox:
    type: "checkbox"
    weight: 30
    value: false
    label: "Install on all compute"
    description: "If true the plugin will install docker on all computes"
